### PR TITLE
Project Structure

### PR DESCRIPTION
**Pull request by simplytunde**
This is basically another attempt to structure our folder. Better ideas?

@dabsclement @adefemi171 @Robogeek95 @phawazzzy @nextwebb @AminuIsrael

### CODE REVIEW

**Review by nextwebb — COMMENTED** [review]
okay this could work. though I would have preferred "client" in place of "frontend". 
@simplytunde

**Comment by dabsclement** [comment]
in addition to what @nextwebb said I think the package.json file should be inside the client/frontedn folder

**Comment by simplytunde** [comment]
> in addition to what @nextwebb said I think the package.json file should be inside the client/frontedn folder

My understanding is configuration/installation files like package.json should be in root folder. At least that is the standard practice of many major projects https://github.com/tektoncd/dashboard  https://github.com/kubernetes/dashboard

**Comment by simplytunde** [comment]
> okay this could work. though I would have preferred "client" in place of "frontend".
> @simplytunde

renamed

**Pull request merged**
