### PR TITLE
CLA GHA

### LINKED ISSUE #57: Add CLA Github Actions
We need a Github Action that ensure contributors signed CLA.
relates #23

### PR DESCRIPTION
**Pull request by adefemi171**
Closes #57

### CODE REVIEW

**Comment by simplytunde** [comment]
@adefemi171 You should be unblocked now.

**Comment by adefemi171** [comment]
@simplytunde just made the changes, please help review

**Comment by simplytunde** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by simplytunde** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by simplytunde** [comment]
@adefemi171  Please sign the CLA to confirm that the job will pass.

**Comment by simplytunde** [comment]
recheck

**Comment by simplytunde** [comment]
recheck

**Comment by simplytunde** [comment]
The file was successfully created. https://github.com/WuraLab/Boardly/blob/signature/signatures/version1/cla.json

**Comment by simplytunde** [comment]
recheck

**Review by simplytunde — APPROVED** [review]

**Comment by adefemi171** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by simplytunde** [comment]
recheck

**Pull request merged**
