### PR TITLE
Login UI #18

### PR DESCRIPTION
**Pull request by dabsclement**
Screenshot from 2021-02-27 13-36-20

### CODE REVIEW

**Comment by dabsclement** [comment]
Screenshot from 2021-03-11 09-34-02
New UI update

**Review by AminuIsrael — DISMISSED** [review]

**Comment by dabsclement** [comment]
Screenshot from 2021-03-23 22-18-58

@simplytunde @Robogeek95 @nextwebb  Kindly review.

**Comment by nextwebb** [comment]
you've got code conflict

**Comment by dabsclement** [comment]
> you've got code conflict

**Comment by dabsclement** [comment]
> you've got code conflict

I have fixed the conflict, please the eslint script I pull from one of your branches is throwing this codacy error shits.. @nextwebb

**Comment by nextwebb** [comment]
> > you've got code conflict
> 
> I have fixed the conflict, please the eslint script I pull from one of your branches is throwing this codacy error @nextwebb

hmmm...

**Comment by nextwebb** [comment]
probably try a fresh clone and merge the default branch to your current branch then fix all the conflicts and push to the upstream branch again. @dabsclement

**Pull request closed without merging**
