### PR TITLE
GHA vulnerability scan

### LINKED ISSUE #34: GHA Vulnerability Scan
There should be a GHA job that scans the application for vulnerability on web and Backend

### PR DESCRIPTION
**Pull request by nextwebb**
Closes  #34 . Vulnerability Scan workflow using Using Trivy to scan your Git repo

### CODE REVIEW

**Comment by nextwebb** [comment]
@simplytunde I'll need Boardly Snyk token. https://github.com/snyk/actions#getting-your-snyk-token
`env:
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}`

**Review by adefemi171 — COMMENTED** [review]
@nextwebb is it possible to merge this file together with the one for backend and probably give it a name that covers both, maybe vscan.yml, also check my comment from this [PR](https://github.com/WuraLab/Boardly/pull/95)

**Comment by nextwebb** [comment]
> @nextwebb is it possible to merge this file together with the one for backend and probably give it a name that covers both, maybe vscan.yml, also check my comment from this [PR](https://github.com/WuraLab/Boardly/pull/95)

I did some research and it said , one job one GHA. that's why I splitted it.

**Comment by adefemi171** [comment]
That's only if the job has two different image and even at that you can use composite job, but my suggestion is that you have one file, two jobs say job web, job backend then they both share the same env variable that could be made global and that will solve having to split the job into two different files. @simplytunde what do you think?

**Comment by nextwebb** [comment]
> That's only if the job has two different image and even at that you can use composite job, but my suggestion is that you have one file, two jobs say job web, job backend then they both share the same env variable that could be made global and that will solve having to split the job into two different files. Imagine we had a different file for linting go and then running test for go,that'll make the workflow folder bulky, it's just an opinion though. Can be put up for review

okay, lemme refactor

**Comment by nextwebb** [comment]
@adefemi171 I've made updates to the GHA

**Comment by adefemi171** [comment]
> @adefemi171 I've made updates to the GHA

Neat.

**Comment by nextwebb** [comment]
@adefemi171 @simplytunde @AminuIsrael can you review my gha!

**Review by AminuIsrael — APPROVED** [review]

**Review by dabsclement — APPROVED** [review]

**Comment by nextwebb** [comment]
@adefemi171 would be out of practice to have another vulnerability scan gha?

**Pull request merged**
