### PR TITLE
Ft create admin UI

### LINKED ISSUE #17: Create Admin UI

### PR DESCRIPTION
**Pull request by phawazzzy**
close #17 

Screenshot 2021-02-27 at 18 12 50

Updated Ui
WhatsApp Image 2021-03-06 at 3 00 48 PM

Added show password icon and functionality
Screenshot 2021-03-18 at 10 31 46

### CODE REVIEW

**Comment by Robogeek95** [comment]
Great!

**Comment by Robogeek95** [comment]
Great!

**Comment by Robogeek95** [comment]
But can you include the peep icon all through for the password fields, it doesn't really seem nice to have it on just one part of the app

**Review by simplytunde — APPROVED** [review]

**Comment by phawazzzy** [comment]
closes #40

**Pull request closed without merging**
